spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'gimyongjun414@gmail.com'
    password: 'uaae kceo ihwr croz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true