spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'gimyongjun414@gmail.com'
    password: 'uaae kceo ihwr croz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306test?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.kyj.fmk.core.controller
    configuration:
      map-underscore-to-camel-case: true

s3:
  credentials:
    access-key: ''
    secret-key: ''
    region: ap-northeast-2  # 예: 서울 리전
    bucket: ''


