spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'gimyongjun414@gmail.com'
    password: 'uaae kceo ihwr croz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
s3:
  credentials:
    access-key: ''
    secret-key: ''
    region: ap-northeast-2  # 예: 서울 리전
    bucket: ''